<?php

/** @var \Magento\Quote\Model\Quote\Item $_item */
$item = $block->getItem();

/** @var \Magento\Catalog\Model\Product $product */
$product = $item->getProduct();

/** @var \Magento\Quote\Model\Quote $quote */
$quote = $item->getQuote();

$productType = $product->getTypeId();

$categoryName = '';

if ($category = $product->getCategory()) {
  $categoryName = $category->getName();
}

$viewModel = $block->getData('viewModel');

$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionCartOfferEnabled();
?>

<?php if ($shouldRender) : ?>
  <div>
    <div class="product-protection-offer" id="product_protection_offer_<?= $product->getSku() ?>"></div>
  </div>
  <script type="text/x-magento-init">
    {
        "#product_protection_offer_<?= $product->getSku() ?>": {
            "simpleProductProtectionOffer": [
               {
                        "extendStoreUuid": "<?= $block
                                              ->getData('viewModel')
                                              ->getExtendStoreUuid() ?>",
                        "activeEnvironment": "<?= $block
                                                ->getData('viewModel')
                                                ->getActiveEnvironment() ?>",
                        "selectedProductSku": "<?= $product->getSku() ?>",
                        "selectedProductPrice": "<?= $product->getPrice() ?>",
                        "productCategory": "<?= $categoryName ?>"
                    }
            ]
        }
    }
</script>
<?php endif; ?>
