<?php
/*
 * Copyright Extend (c) 2023. All rights reserved.
 * See Extend-COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */

$categoryName = '';

if ($category = $block->getProduct()->getCategory()) {
  $categoryName = $category->getName();
}

$viewModel = $block->getData('viewModel');

$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionProductDisplayPageOfferEnabled();
?>

<?php if ($shouldRender) : ?>
  <div class="product-protection-offer" id="product_protection_offer_<?= rawurlencode($block->getProduct()->getSku()); ?>"></div>
  <script type="text/x-magento-init">
    {
          "#product_protection_offer_<?= rawurlencode($block->getProduct()->getSku()); ?>": {
              "productProtectionOffer": [
                  {
                      "extendStoreUuid": "<?= $block->getData('viewModel')->getExtendStoreUuid() ?>",
                      "activeEnvironment": "<?= $block->getData('viewModel')->getActiveEnvironment() ?>",
                      "selectedProductSku": "<?= $block->getProduct()->getSku(); ?>",
                      "selectedProductPrice": "<?= $block->getProduct()->getPrice(); ?>",
                      "productCategory": "<?= $categoryName; ?>"
                  }
              ]
          }
      }
  </script>
<?php endif; ?>
