<?php
$viewModel = $block->getData('viewModel');

$extendStoreUuid = $viewModel->getExtendStoreUuid();
$activeEnvironment = $viewModel->getActiveEnvironment();

/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getProduct();
$productSku = $product->getSku();
/** encoding to prevent whitespace and other abnormal characters from being used in a div id */
$encodedProductSku = rawurlencode($productSku);
$productPrice = $product->getPrice();

$categoryName = '';
if ($category = $product->getCategory()) {
  $categoryName = $category->getName();
}

$viewModel = $block->getData('viewModel');

$shouldRender = $viewModel->isExtendProductProtectionEnabled() && $viewModel->isProductProtectionProductCatalogPageModalOfferEnabled();
?>

<?php if ($shouldRender) : ?>
  <div class="product_protection_modal_offer" id="product_protection_modal_offer_<?= $encodedProductSku ?>"></div>

  <script type="text/x-magento-init">
    {
          "#product_protection_modal_offer_<?= $encodedProductSku ?>": {
              "productProtectionModalOffer": [
                  {
                      "extendStoreUuid": "<?= $extendStoreUuid ?>",
                      "activeEnvironment": "<?= $activeEnvironment ?>",
                      "productSku": "<?= $productSku ?>",
                      "productPrice": "<?= $productPrice ?>",
                      "productCategory": "<?= $categoryName ?>"
                  }
              ]
          }
      }
  </script>
<?php endif; ?>
